{
  "swagger": "2.0",
  "info": {
    "description": "This is an API to query about FIFA players and teams exposing some interesting functionalities that aim to be useful in real-life scenarios. This project was developed as a final exam for 'Base de Datos 2' at ITBA",
    "version": "1.0.0",
    "title": "FInest Football Analizer",
    "contact": {
      "name": "Round Robin (Quintairos, Revich, Sicardi)"
    }
  },
  "externalDocs": {
    "description": "Project repository",
    "url": "https://github.com/Jsicardi/Round_Robin_Final_BD2_2C_2021"
  },
  "host": "localhost:3000",
  "basePath": "/api",
  "tags": [
    {
      "name": "players",
      "description": "Everything about players"
    },
    {
      "name": "teams",
      "description": "Everything about teams"
    },
    {
      "name": "national teams",
      "description": "Everything about national teams"
    },
    {
      "name": "leagues",
      "description": "Everything about leagues"
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/players": {
      "get": {
        "tags": [
          "players"
        ],
        "summary": "Finds players filtered by different attributes",
        "description": "Return players that fulfill the different qualities paginated",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "age",
            "in": "query",
            "description": "The upper-limit age of the players",
            "required": false,
            "type": "integer"
          },
          {
            "name": "nationality",
            "in": "query",
            "description": "The nationality of the players",
            "required": false,
            "type": "string"
          },
          {
            "name": "preferredFoot",
            "in": "query",
            "description": "The preferred foot of the players ('Left' or 'Right')",
            "required": false,
            "type": "string"
          },
          {
            "name": "valueEUR",
            "in": "query",
            "description": "The lower-limit value in Euros of the players",
            "required": false,
            "type": "integer"
          },
          {
            "name": "position",
            "in": "query",
            "description": "A position a player can play from",
            "required": false,
            "type": "string"
          },
          {
            "name": "remainingTime",
            "in": "query",
            "description": "The upper-limit of years remaining of the player in the team",
            "required": false,
            "type": "integer"
          },
          {
            "name": "name",
            "in": "query",
            "description": "The name of the player (Returns players with name similar to this)",
            "required": false,
            "type": "string"
          },
          {
            "name": "page",
            "in": "query",
            "description": "The required page of players",
            "required": false,
            "type": "integer",
            "default": 1
          },
          {
            "name": "limit",
            "in": "query",
            "description": "The limit of players by page",
            "required": false,
            "type": "integer",
            "default": 3
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/PlayerFull"
              },
              "example": [
                {
                  "player_id": 204485,
                  "fullname": "Riyad Mahrez",
                  "age": 30,
                  "photo": "https://photo.png",
                  "nationality": "Algeria",
                  "total_score": 86,
                  "positions": "['RW', 'RM']",
                  "bestPosition": "RW",
                  "team_id": 10,
                  "value_eur": 65500000,
                  "contract_until": 2023,
                  "national_team_id": 4,
                  "preferred_foot": "Left",
                  "pace_total": 81,
                  "shooting_total": 80,
                  "passing_total": 81,
                  "dribbling_total": 90,
                  "defending_total": 38,
                  "physicality_total": 60,
                  "team_uri": "http://localhost:3000/api/teams/10"
                },
                {
                  "player_id": 200260,
                  "fullname": "Steven Berghuis",
                  "age": 29,
                  "photo": "https://photo.png",
                  "nationality": "Netherlands",
                  "total_score": 81,
                  "positions": "['RW']",
                  "bestPosition": "RW",
                  "team_id": 245,
                  "value_eur": 65500000,
                  "contract_until": 2023,
                  "national_team_id": 4,
                  "preferred_foot": "Left",
                  "pace_total": 80,
                  "shooting_total": 81,
                  "passing_total": 82,
                  "dribbling_total": 82,
                  "defending_total": 36,
                  "physicality_total": 66,
                  "team_uri": "http://localhost:3000/api/teams/245",
                  "national_team_uri": "http://localhost:3000/api/nationalTeams/105035"
                },
                {
                  "player_id": 183898,
                  "fullname": "Ángel Di María",
                  "age": 33,
                  "photo": "https://photo.png",
                  "nationality": "Argentina",
                  "total_score": 87,
                  "positions": "['RW', 'LW']",
                  "bestPosition": "RW",
                  "team_id": 73,
                  "value_eur": 65500000,
                  "contract_until": 2023,
                  "national_team_id": 1369,
                  "preferred_foot": "Left",
                  "pace_total": 83,
                  "shooting_total": 81,
                  "passing_total": 86,
                  "dribbling_total": 88,
                  "defending_total": 48,
                  "physicality_total": 69,
                  "team_uri": "http://localhost:3000/api/teams/73",
                  "national_team_uri": "http://localhost:3000/api/nationalTeams/1369"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request ( For example age < 0 )"
          }
        }
      }
    },
    "/players/{id}": {
      "get": {
        "tags": [
          "players"
        ],
        "summary": "Find a specific player",
        "description": "Return player that matches id",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the player",
            "required": true,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "example": {
                "player_id": 183898,
                "fullname": "Ángel Di María",
                "age": 33,
                "photo": "https://photo.png",
                "nationality": "Argentina",
                "total_score": 87,
                "positions": "['RW', 'LW']",
                "bestPosition": "RW",
                "team_id": 73,
                "value_eur": 65500000,
                "contract_until": 2023,
                "national_team_id": 1369,
                "preferred_foot": "Left",
                "pace_total": 83,
                "shooting_total": 81,
                "passing_total": 86,
                "dribbling_total": 88,
                "defending_total": 48,
                "physicality_total": 69,
                "team_uri": "http://localhost:3000/api/teams/73",
                "national_team_uri": "http://localhost:3000/api/nationalTeams/1369"
              }
            }
          },
          "400": {
            "description": "Bad Request ( For example invalid path parameter )"
          }
        }
      }
    },
    "/players/similar": {
      "get": {
        "tags": [
          "players"
        ],
        "summary": "Finds players with the same playing style as the one passed",
        "description": "Return players that perform the closest to the one passed in FIFA's categories (Pace, dribbling, shooting, passing, defending, physicality) and plays in the same position",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "description": "Player name trying to find similar players for",
            "required": true,
            "type": "string"
          },
          {
            "name": "page",
            "in": "query",
            "description": "The required page of players",
            "required": false,
            "type": "integer",
            "default": 1
          },
          {
            "name": "limit",
            "in": "query",
            "description": "The limit of players by page",
            "required": false,
            "type": "integer",
            "default": 3
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/PlayerFull"
              },
              "example": [
                {
                  "player_id": 204485,
                  "fullname": "Riyad Mahrez",
                  "age": 30,
                  "photo": "https://photo.png",
                  "nationality": "Algeria",
                  "total_score": 86,
                  "positions": "['RW', 'RM']",
                  "bestPosition": "RW",
                  "team_id": 10,
                  "value_eur": 65500000,
                  "contract_until": 2023,
                  "national_team_id": 4,
                  "preferred_foot": "Left",
                  "pace_total": 81,
                  "shooting_total": 80,
                  "passing_total": 81,
                  "dribbling_total": 90,
                  "defending_total": 38,
                  "physicality_total": 60,
                  "team_uri": "http://localhost:3000/api/teams/10"
                },
                {
                  "player_id": 200260,
                  "fullname": "Steven Berghuis",
                  "age": 29,
                  "photo": "https://photo.png",
                  "nationality": "Netherlands",
                  "total_score": 81,
                  "positions": "['RW']",
                  "bestPosition": "RW",
                  "team_id": 245,
                  "value_eur": 65500000,
                  "contract_until": 2023,
                  "national_team_id": 4,
                  "preferred_foot": "Left",
                  "pace_total": 80,
                  "shooting_total": 81,
                  "passing_total": 82,
                  "dribbling_total": 82,
                  "defending_total": 36,
                  "physicality_total": 66,
                  "team_uri": "http://localhost:3000/api/teams/245",
                  "national_team_uri": "http://localhost:3000/api/nationalTeams/105035"
                },
                {
                  "player_id": 183898,
                  "fullname": "Ángel Di María",
                  "age": 33,
                  "photo": "https://photo.png",
                  "nationality": "Argentina",
                  "total_score": 87,
                  "positions": "['RW', 'LW']",
                  "bestPosition": "RW",
                  "team_id": 73,
                  "value_eur": 65500000,
                  "contract_until": 2023,
                  "national_team_id": 1369,
                  "preferred_foot": "Left",
                  "pace_total": 83,
                  "shooting_total": 81,
                  "passing_total": 86,
                  "dribbling_total": 88,
                  "defending_total": 48,
                  "physicality_total": 69,
                  "team_uri": "http://localhost:3000/api/teams/73",
                  "national_team_uri": "http://localhost:3000/api/nationalTeams/1369"
                }
              ]
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/players/nationalityPartners": {
      "get": {
        "tags": [
          "players"
        ],
        "summary": "Finds recommendations for national teams",
        "description": "Return players that play or have played with players that are currently representing their national team",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "player",
            "in": "query",
            "description": "Player name that currently plays in national team to search for his partners",
            "required": true,
            "type": "string"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "The limit of players to retrieve",
            "required": false,
            "type": "integer",
            "default": 3
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Player"
              },
              "example": [
                {
                  "player_id": 170368,
                  "name": "Erik Lamela"
                },
                {
                  "player_id": 205632,
                  "name": "Lucas Ocampos"
                },
                {
                  "player_id": 228711,
                  "name": "Brian Mansilla"
                }
              ]
            }
          },
          "400": {
            "description": "Missing player parameter"
          }
        }
      }
    },
    "/players/degrees": {
      "get": {
        "tags": [
          "players"
        ],
        "summary": "N degrees of player (Six degrees of Bacon)",
        "description": "Return players that are up to n jumps away from the player passed. (1 degree are players that played with player passed. 2 degrees are the 1 degree players and players 1 degree away from them. And so on.)",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "player",
            "in": "query",
            "description": "Player name to calculate degrees of",
            "required": true,
            "type": "string"
          },
          {
            "name": "degrees",
            "in": "query",
            "description": "Degrees requested",
            "required": true,
            "type": "integer",
            "minimum": 1,
            "maximum": 6
          },
          {
            "name": "limit",
            "in": "query",
            "description": "The limit of players to retrieve",
            "required": false,
            "type": "integer",
            "default": 100
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Player"
              },
              "example": [
                {
                  "player_id": 155862,
                  "name": "Sergio Ramos García"
                },
                {
                  "player_id": 201399,
                  "name": "Mauro Icardi"
                },
                {
                  "player_id": 231747,
                  "name": "Kylian Mbappé"
                }
              ]
            }
          },
          "400": {
            "description": "Missing player parameter - Missing degrees parameter - Invalid degrees value, should be an integer between 1 and 6"
          }
        }
      }
    },
    "/teams": {
      "get": {
        "tags": [
          "teams"
        ],
        "summary": "Finds teams sorted by criteria passed",
        "description": "Return teams that fulfill the different qualities paginated",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sortBy",
            "in": "query",
            "description": "Attribute to sort by (transferBudget - teamAverageAge)",
            "required": false,
            "type": "string"
          },
          {
            "name": "order",
            "in": "query",
            "description": "Ascending or descending (asc - desc)",
            "required": false,
            "type": "string"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "The limit of teams by page",
            "required": false,
            "type": "integer",
            "default": 3
          },
          {
            "name": "page",
            "in": "query",
            "description": "The page of teams requested",
            "required": false,
            "type": "integer",
            "default": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Team"
              },
              "example": [
                {
                  "team_id": "10",
                  "team_name": "Manchester City",
                  "league": "English Premeier League",
                  "transfer_budget": "176000000",
                  "team_average_age": "23.9"
                },
                {
                  "team_id": "11",
                  "team_name": "Manchester United",
                  "league": "English Premeier League",
                  "transfer_budget": "175000000",
                  "team_average_age": "25.9"
                },
                {
                  "team_id": "73",
                  "team_name": "Paris Saint-Germain",
                  "league": "French Ligue 1",
                  "transfer_budget": "160000000",
                  "team_average_age": "25.9"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request ( For example invalid query parameter )"
          }
        }
      }
    },
    "/teams/{id}": {
      "get": {
        "tags": [
          "teams"
        ],
        "summary": "Find a specific team",
        "description": "Return team that matches id",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the team",
            "required": true,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "example": {
                "team_id": "10",
                "team_name": "Manchester City",
                "league": "English Premeier League",
                "transfer_budget": "176000000",
                "team_average_age": "23.9"
              }
            }
          },
          "400": {
            "description": "Bad Request ( For example invalid path parameter )"
          }
        }
      }
    },
    "/teams/recommended": {
      "get": {
        "tags": [
          "teams"
        ],
        "summary": "Finds recommended teams for a player to play in",
        "description": "Return teams where current player's partners have played in the past",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "player",
            "in": "query",
            "description": "Player name that is looking for team recommendations",
            "required": true,
            "type": "string"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "The limit of teams to retrieve",
            "required": false,
            "type": "integer",
            "default": 3
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/TeamAndCount"
              },
              "example": [
                {
                  "club_id": 243,
                  "club": "Real Madrid CF",
                  "timesMatched": 4
                },
                {
                  "club_id": 69,
                  "club": "AS Monaco",
                  "timesMatched": 4
                },
                {
                  "club_id": 47,
                  "club": "AC Milan",
                  "timesMatched": 3
                }
              ]
            }
          },
          "400": {
            "description": "Missing player parameter"
          }
        }
      }
    },
    "/nationalTeams": {
      "get": {
        "tags": [
          "national teams"
        ],
        "summary": "Finds national teams",
        "description": "Return national teams stored in database",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "The limit of national teams by page",
            "required": false,
            "type": "integer",
            "default": 3
          },
          {
            "name": "page",
            "in": "query",
            "description": "The page of national teams requested",
            "required": false,
            "type": "integer",
            "default": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/NationalTeam"
              },
              "example": [
                {
                  "national_team_id": "1369",
                  "national_team_name": "Argentina"
                },
                {
                  "national_team_id": "1415",
                  "national_team_name": "Australia"
                },
                {
                  "national_team_id": "1322",
                  "national_team_name": "Austria"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request ( For example invalid query parameter )"
          }
        }
      }
    },
    "/nationalTeams/{id}": {
      "get": {
        "tags": [
          "national teams"
        ],
        "summary": "Find a specific national team",
        "description": "Return national team that matches id",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the national team",
            "required": true,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "example": {
                "national_team_id": "1369",
                "national_team_name": "Argentina"
              }
            }
          },
          "400": {
            "description": "Bad Request ( For example invalid path parameter )"
          }
        }
      }
    },
    "/leagues": {
      "get": {
        "tags": [
          "leagues"
        ],
        "summary": "Finds leagues sorted by criteria passed",
        "description": "Return leagues that fulfill the different qualities paginated",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sortBy",
            "in": "query",
            "description": "Attribute to sort by (transferBudget - teamAverageAge - nationalTeamPlayers)",
            "required": false,
            "type": "string"
          },
          {
            "name": "order",
            "in": "query",
            "description": "Ascending or descending (asc - desc)",
            "required": false,
            "type": "string"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "The limit of leagues by page",
            "required": false,
            "type": "integer",
            "default": 3
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/League"
              },
              "example": [
                {
                  "league": "English Premier League",
                  "team_count": "20",
                  "average_transfer_budget": "57798589.34",
                  "average_age": "25",
                  "national_team_players_count": "128"
                },
                {
                  "league": "Spain Primera Division",
                  "team_count": "20",
                  "average_transfer_budget": "30563022.51",
                  "average_age": "26",
                  "national_team_players_count": "50"
                },
                {
                  "league": "German 1. Bundesliga",
                  "team_count": "18",
                  "average_transfer_budget": "27935218.98",
                  "average_age": "24",
                  "national_team_players_count": "71"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request ( For example invalid query parameter )"
          }
        }
      }
    }
  },
  "definitions": {
    "Player": {
      "type": "object",
      "required": [
        "player_id",
        "name"
      ],
      "properties": {
        "player_id": {
          "type": "integer",
          "example": "10"
        },
        "name": {
          "type": "string",
          "example": "Erik Lamela"
        }
      }
    },
    "PlayerFull": {
      "type": "object",
      "required": [
        "player_id",
        "fullname",
        "age",
        "photo",
        "nationality",
        "total_score",
        "positions",
        "bestPosition",
        "team_id",
        "value_eur",
        "contract_until",
        "national_team_id",
        "preferred_foot",
        "pace_total",
        "shooting_total",
        "passing_total",
        "dribbling_total",
        "defending_total",
        "physicality_total",
        "team_uri"
      ],
      "properties": {
        "player_id": {
          "type": "integer",
          "example": 204485
        },
        "fullname": {
          "type": "string",
          "example": "Riyad Mahrez"
        },
        "age": {
          "type": "integer",
          "example": 30
        },
        "photo": {
          "type": "string",
          "example": "https://photo.png"
        },
        "nationality": {
          "type": "string",
          "example": "Algeria"
        },
        "total_score": {
          "type": "integer",
          "example": 86
        },
        "positions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "RW",
            "RM"
          ]
        },
        "bestPosition": {
          "type": "string",
          "example": "RW"
        },
        "team_id": {
          "type": "integer",
          "example": 10
        },
        "value_eur": {
          "type": "integer",
          "example": 65500000
        },
        "contract_until": {
          "type": "integer",
          "example": 2023
        },
        "national_team_id": {
          "type": "integer",
          "example": 4
        },
        "preferred_foot": {
          "type": "string",
          "example": "Left"
        },
        "pace_total": {
          "type": "integer",
          "example": 81
        },
        "shooting_total": {
          "type": "integer",
          "example": 80
        },
        "passing_total": {
          "type": "integer",
          "example": 81
        },
        "dribbling_total": {
          "type": "integer",
          "example": 90
        },
        "defending_total": {
          "type": "integer",
          "example": 38
        },
        "physicality_total": {
          "type": "integer",
          "example": 60
        },
        "team_uri": {
          "type": "string",
          "example": "http://localhost:3000/api/teams/10"
        },
        "national_team_uri": {
          "type": "string",
          "example": "http://localhost:3000/api/nationalTeams/1369"
        }
      }
    },
    "TeamAndCount": {
      "type": "object",
      "required": [
        "club_id",
        "club",
        "timesMatched"
      ],
      "properties": {
        "club_id": {
          "type": "integer",
          "example": 243
        },
        "club": {
          "type": "string",
          "example": "Real Madrid CF"
        },
        "timesMatched": {
          "type": "integer",
          "example": 4
        }
      }
    },
    "Team": {
      "type": "object",
      "required": [
        "team_id",
        "team_name",
        "league",
        "transfer_budget",
        "team_average_age"
      ],
      "properties": {
        "team_id": {
          "type": "integer",
          "example": "10"
        },
        "team_name": {
          "type": "string",
          "example": "Manchester City"
        },
        "league": {
          "type": "string",
          "example": "English Premeier League"
        },
        "transfer_budget": {
          "type": "integer",
          "example": "176000000"
        },
        "team_average_age": {
          "type": "number",
          "example": "23.9"
        }
      }
    },
    "NationalTeam": {
      "type": "object",
      "required": [
        "national_team_id",
        "national_team_name"
      ],
      "properties": {
        "national_team_id": {
          "type": "integer",
          "example": "1369"
        },
        "national_team_name": {
          "type": "string",
          "example": "Argentina"
        }
      }
    },
    "League": {
      "type": "object",
      "required": [
        "league",
        "team_count",
        "total_transfer_budget",
        "average_age",
        "national_team_players_count"
      ],
      "properties": {
        "league": {
          "type": "string",
          "example": "Chinese Super League"
        },
        "team_count": {
          "type": "string",
          "example": "24"
        },
        "average_transfer_budget": {
          "type": "string",
          "example": "10150000.00"
        },
        "average_age": {
          "type": "integer",
          "example": "27"
        },
        "national_team_players_count": {
          "type": "string",
          "example": "24"
        }
      }
    }
  }
}